language: cpp

sudo: required

branches:
  only:
  - master
  - devel

matrix:
  include:
  # minimal gcc version (also on loewe cluster)
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - libboost-all-dev
          - g++-4.8
    env:
      - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
  # more recent gcc (most recent on loewe)
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - libboost-all-dev
          - g++-5
    env:
      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
  # new gcc version
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - libboost-all-dev
          - g++-8
    env:
      - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
  # clang on linux
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6
        packages:
          - libboost-all-dev
          - clang-3.6
    env:
      - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
  # most recent xcode (changes also clang version)
  - os: osx
    osx_image: xcode10
    addons:
      homebrew:
        packages:
        - boost
    env:
      - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - export SMASH_ROOT=$(pwd)
  # clang-format
  - if [ $TRAVIS_OS_NAME = osx ]; then curl -# -o clang6_0_0.tar.xz http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-apple-darwin.tar.xz;
    else  curl -# -o clang6_0_0.tar.xz http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz; fi &&
    mkdir clang6_0_0 && tar -xf clang6_0_0.tar.xz -C clang6_0_0 --strip-components=1 &&
    export PATH=$SMASH_ROOT/clang6_0_0/bin/:$PATH
  # gsl
  - wget http://ftpmirror.gnu.org/gsl/gsl-1.15.tar.gz &&
    tar -zxf gsl-1.15.tar.gz &&
    export GSL=$(pwd)/gsl-1.15 &&
    cd $GSL &&
    ./configure --prefix $GSL &&
    make -j2 --silent &&
    make install --silent &&
    cd $SMASH_ROOT
  # eigen
  - wget http://bitbucket.org/eigen/eigen/get/3.3.5.tar.gz &&
    tar -xf 3.3.5.tar.gz -C $HOME
  # cpplint
  - pip install --user cpplint

install:
  - cd $SMASH_ROOT
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/eigen-eigen-b3f3d4950030/ -DGSL_ROOT_DIR=$GSL ..
  - make -j2

script:
  - ctest -j2
  - ./../bin/clang-format-helper.sh -t
