Logging:
    default: OFF

General:
    Modus:         Box
    Time_Step_Mode: Fixed
    Delta_Time:    0.1
    End_Time:      100.0
    Randomseed:    -1
    Nevents:       100

Output:
    Output_Interval: 5.0
    Particles:
        Format:          ["Oscar2013"]
        Only_Final:      No

Modi:
    Box:
        Start_Time: 0.0
        Length: 10.0
        Temperature: 0.15
        Initial_Condition: "thermal momenta"
        # The box is initialized with the particles listed in particles.txt
        # according to their expected thermal multiplicities at the temperature
        # specified above.
        Use_Thermal_Multiplicities: True

Collision_Term:
    Total_Cross_Section_Strategy: "BottomUp"
    Pseudoresonance: "None"
    Force_Decays_At_End: False
    Strings: False
    NNbar_Treatment: "resonances"
    Elastic_NN_Cutoff_Sqrts: 1.8
