Version: 1.8
# change together with potentials config
Logging:
    default: OFF

General:
    Modus:         Collider
    Time_Step_Mode: Fixed
    Delta_Time:    0.1
    End_Time:      50.0
    Randomseed:    -1
    Nevents:       5
    Testparticles: 20


Output:
    Particles:
        Format:          ["Oscar2013"]

Modi:
    Collider:
        Projectile:
            Particles: {2212: 29, 2112: 35} #Cu64
        Target:
            Particles: {2212: 29, 2112: 35} #Cu64

        E_Kin: 1.23
        Fermi_Motion: frozen
