Version: 2.2
Logging:
    default: OFF

General:
    Modus:         Collider
    Time_Step_Mode: Fixed
    Delta_Time:    0.1
    End_Time:      200.0
    Randomseed:    -1
    Nevents:       5

Output:
    Particles:
        Format:          ["Oscar2013"]

Modi:
    Collider:
        Projectile:
            Particles: {2212: 29, 2112: 35} #Cu64
        Target:
            Particles: {2212: 29, 2112: 35} #Cu64


        Sqrtsnn: 200.0
        Fermi_Motion: "frozen"
