Version: 1.5
# change together with testparticles config
Logging:
    default: OFF

General:
    Modus:         Collider
    Time_Step_Mode: Fixed
    Delta_Time:    0.1
    End_Time:      50.0
    Randomseed:    -1
    Nevents:       5
    Testparticles: 20


Output:
    Particles:
        Format:          ["Oscar2013"]

Modi:
    Collider:
        Projectile:
            Particles: {2212: 29, 2112: 35} #Cu64
        Target:
            Particles: {2212: 29, 2112: 35} #Cu64

        E_Kin: 1.23
        Fermi_Motion: on

Potentials:
    Skyrme:
        Skyrme_A: -209.2
        Skyrme_B: 156.4
        Skyrme_Tau: 1.35
    Symmetry:
        S_Pot: 18.0

Collision_Term:
    Pauli_Blocking:
        Spatial_Averaging_Radius:   1.86
        Momentum_Averaging_Radius:  0.08
        Gaussian_Cutoff:            2.2
