Logging:
    default: INFO

General:
    Modus:         Box
    Time_Step_Mode: Fixed
    Delta_Time:    0.1
    End_Time:      200.0
    Randomseed:    -1
    Nevents:       30

Output:
    Photons:
        Format: ["Oscar2013"]

Modi:
    Box:
        Start_Time: 0.0
        Length: 10.0
        Temperature: 0.15
        Initial_Condition: "thermal momenta"
        Use_Thermal_Multiplicities: True

Collision_Term:
    Total_Cross_Section_Strategy: "BottomUp"
    Pseudoresonance: "None"
    Force_Decays_At_End: False
    Strings: False
    Elastic_Cross_Section:  30.0
    Photons:
        2to2_Scatterings: True
        Bremsstrahlung: True
        Fractional_Photons: 100
