General:
    # Modus decision
    MODUS:         Nucleus

    # temporal grid spacing
    DELTA_TIME:    0.01

    # end time of simulation
    END_TIME:      100.0

    # how much time before recording measurables
    OUTPUT_INTERVAL:  1.0

    # initial random seed (negative for time)
    RANDOMSEED:    -1

    # elastic cross section
    SIGMA:         10.0

    # number of test particle
    TESTPARTICLES: 1

    # number of events
    NEVENTS:       1

Modi:
    Box:
        # Cube size
        LENGTH: 10.0

        # initialization temperature
        TEMPERATURE: 0.2

        # initial condition
        #
        # 1:  random position box + thermal momenta
        # 2:  random position box + peaked momenta
        #
        INITIAL_CONDITION: 1

        # start time of simulation
        START_TIME:    0.0

    Sphere:
        # Sphere size
        RADIUS: 5.0

    Collider:
        # Projectile particle
        PROJECTILE: 211

        # Target particle
        TARGET: -211

        # center-of-mass energy in GeV
        SQRTS: 1.0

    Nucleus:
        # Set up a copper-gold collision.
        # Definitions for the projectile:
        Projectile:
            PARTICLES: {2212: 29, 2112: 34}
            AUTOMATIC: false
            DEFORMED: false
        # Definitions for the target:
        Target:
            PARTICLES: {2212: 79, 2112: 118}
            AUTOMATIC: false
            DEFORMED: false
        # what sqrt(s_NN) to use:
        SQRTSNN: 10
        # the reference frame
        CALCULATION_FRAME: 3
        # which subsystem "NN" in sqrt(s_NN) refers to
        # (two PDG IDs). The default is proton-proton; let's set it to
        # neutron-neutron.
        SQRTS_N: [2112, 2112]
        # impact parameter (we'll sample from a distribution
        # between 0 and 10)
        Impact:
            MAX: 10
        INITIAL_DISTANCE: 60
