General:
    # Modus decision
    MODUS:         Box

    # temporal grid spacing
    DELTA_TIME:    0.1

    # end time of simulation
    END_TIME:      1.0

    # output formats
    OUTPUT:
        OSCAR_COLLISIONS:
            Enable:             True
            2013_format:        True
            Print_start_end:    False
        OSCAR_PARTICLELIST:
            Enable:             True
            2013_format:        True
            Only_final:         True
        VTK:
            Enable:             False
        ROOT:
            Enable:             True
            write_collisions:   True
            write_particles:    True
            autosave_frequency: 1000
        Binary_collisions:
            Enable:             True
            print_start_end:    True
        Binary_particles:
            Enable:             True
            only_final:         False

    # how much time before recording measurables
    OUTPUT_INTERVAL:  1.0

    # initial random seed (negative for time)
    RANDOMSEED:    1

    # elastic cross section
    SIGMA:         10.0

    # number of test particle
    TESTPARTICLES: 1

    # number of events
    NEVENTS:       1

Modi:
    Box:
        # Cube size
        LENGTH: 10.0

        # initialization temperature
        TEMPERATURE: 0.2

        # initial condition
        #
        # 1:  random position box + thermal momenta
        # 2:  random position box + peaked momenta
        #
        INITIAL_CONDITION: 1

        # start time of simulation
        START_TIME:    0.0

        INIT_MULTIPLICITIES:
            221:    100
            111:    200
            2112:   20

    Sphere:
        # Sphere size
        RADIUS: 5.0
        # Number of particles in Sphere
        NUMBEROFPARTICLES: 280
        # Current temperature
        SPHERETEMPERATURE: 0.2
        # start time of simulation
        START_TIME: 0.0

    Collider:
        # Projectile particle
        PROJECTILE: 211

        # Target particle
        TARGET: -211

        # center-of-mass energy in GeV
        SQRTS: 1.0
    Nucleus:
        # Definitions for the projectile:
        # Deuteron
        Projectile:
            PARTICLES: {2212: 1, 2112: 1}
            # very hard Woods-Saxon distribution.
            DIFFUSIVENESS: .001
        # Definitions for the target:
        # Lead
        Target:
            PARTICLES: {2212: 82, 2112: 126}

        # what sqrt(s_NN) to use:
        SQRTSNN: 2
        # which subsystem "NN" in sqrt(s_NN) refers to
        # (two PDG IDs). The default is proton-proton; let's set it to
        # neutron-neutron.
        SQRTS_N: [2112, 2112]
