General:
    # Modus decision
    MODUS:         Nucleus

    # temporal grid spacing
    DELTA_TIME:    0.01

    # end time of simulation
    END_TIME:      1.0

    # output formats
    OUTPUT:
        OSCAR_COLLISIONS:
            Enable:             True
            2013_format:        True
            Print_start_end:    False
        OSCAR_PARTICLELIST:
            Enable:             True
            2013_format:        True
            Only_final:         True
        VTK:
            Enable:             False
        ROOT:
            Enable:             True
            write_collisions:   True
            write_particles:    True
            autosave_frequency: 1000
        Binary_collisions:
            Enable:             True
            print_start_end:    True
        Binary_particles:
            Enable:             True
            only_final:         False

    # how much time before recording measurables
    OUTPUT_INTERVAL:  1.0

    # initial random seed (negative for time)
    RANDOMSEED:    1

    # elastic cross section
    SIGMA:         10.0

    # number of test particle
    TESTPARTICLES: 1

    # number of events
    NEVENTS:       1

Modi:
    Box:
        # Cube size
        LENGTH: 10.0

        # initialization temperature
        TEMPERATURE: 0.2

        # initial condition
        #
        # 1:  random position box + thermal momenta
        # 2:  random position box + peaked momenta
        #
        INITIAL_CONDITION: 1

        # start time of simulation
        START_TIME:    0.0

        INIT_MULTIPLICITIES:
            221:    100
            111:    200
            2112:   20

    Sphere:
        # Sphere size
        RADIUS: 5.0
        # Number of particles in Sphere
        NUMBEROFPARTICLES: 280
        # Current temperature
        SPHERETEMPERATURE: 0.2
        # start time of simulation
        START_TIME: 0.0

    Collider:
        # Projectile particle
        PROJECTILE: 211

        # Target particle
        TARGET: -211

        # center-of-mass energy in GeV
        SQRTS: 1.0

    Nucleus:
        # Set up a copper-gold collision.
        # Definitions for the projectile:
        Projectile:
            PARTICLES: {2212: 29, 2112: 34}
            AUTOMATIC: false
            DEFORMED: false
        # Definitions for the target:
        Target:
            PARTICLES: {2212: 79, 2112: 118}
            AUTOMATIC: true
            DEFORMED: true
        # Collision energy (E_LAB, P_LAB, SQRTSNN).
        # E_LAB : 100
        # P_LAB : 100
        SQRTSNN: 10
        # The representative particles (two PDG IDs) determining the
        # subsystem "NN" in sqrt(s_NN). Let's try neutron-neutron.
        SQRTS_REPS: [2112, 2112]
        # The reference frame in which to do the calculation.
        # (1 = center of velocity, 2 = center of mass, 3 = fixed target)
        CALCULATION_FRAME: 1
        # Impact parameter. We'll sample from a distribution
        # between 0 and 10.
        Impact:
            MAX: 10
