Logging:
  default: INFO
  #Legacy: ALL
  #Main: ALL
  #Experiment: ALL
  #Box: ALL
  #Nucleus: ALL
  #Sphere: ALL
  #ParticleType: ALL
  #Action: ALL
  #FindScatter: ALL
  #DecayModes: ALL
  #ScatterAction: ALL

General:
    # Modus decision
    Modus:         Collider

    # temporal grid spacing
    Delta_Time:    0.01

    # end time of simulation
    End_Time:      1.0

    # output formats
    Output:
        Oscar_Collisions:
            Enable:             True
            2013_Format:        True
            Print_Start_End:    False
        Oscar_Particlelist:
            Enable:             True
            2013_Format:        True
            Only_Final:         True
        Vtk:
            Enable:             False
        Root:
            Enable:             True
            Write_Collisions:   True
            Write_Particles:    True
            Autosave_Frequency: 1000
        Binary_Collisions:
            Enable:             True
            Print_Start_End:    True
        Binary_Particles:
            Enable:             True
            Only_Final:         False

    # how much time before recording measurables
    Output_Interval:  1.0

    # initial random seed (auto-generated if negative)
    Randomseed:    1

    # elastic cross section
    Sigma:         10.0

    # number of test particle
    Testparticles: 1

    # number of events
    Nevents:       1

Collision_Term:
    Decays:        True
    Collisions:    True

Modi:
    Box:
        # Cube size
        Length: 10.0

        # initialization temperature
        Temperature: 0.2

        # initial condition
        #
        # 1:  random position box + thermal momenta
        # 2:  random position box + peaked momenta
        #
        Initial_Condition: 1

        # start time of simulation
        Start_Time:    0.0

        Init_Multiplicities:
            221:    100
            111:    200
            2112:   20

    Sphere:
        # Sphere size
        Radius: 5.0
        # Current temperature
        Sphere_Temperature: 0.2
        # start time of simulation
        Start_Time: 0.0
        # Number of particles in Sphere
        Init_Multiplicities:
            221:    100
            111:    200
            2112:   20


    Collider:
        # Definitions for the projectile:
        # Deuteron
        Projectile:
            Particles: {2212: 1, 2112: 1}
            # very hard Woods-Saxon distribution.
            Diffusiveness: .001
            Automatic: false
            Deformed: false
        # Definitions for the target:
        # Lead
        Target:
            Particles: {2212: 82, 2112: 126}
            Automatic: true
            Deformed: false

        # Collision energy (E_LAB, P_LAB, SQRTSNN).
        Sqrtsnn: 2
        # The representative particles (two PDG IDs) determining the
        # subsystem "NN" in sqrt(s_NN). Let's try neutron-neutron.
        Sqrts_Reps: [2112, 2112]
        # The reference frame in which to do the calculation.
        # (1 = center of velocity, 2 = center of mass, 3 = fixed target)
        Calculation_Frame: 1
