General:
    # Modus decision
    MODUS:         Nucleus

    # temporal grid spacing
    DELTA_TIME:    0.01

    # end time of simulation
    END_TIME:      1.0

    # output formats
    OUTPUT:
        OSCAR_COLLISIONS:
            Enable:             True
            Format:             2013
            Print_start_end:    False
        OSCAR_PARTICLELIST:
            Enable:             True
            Format:             2013
            Only_final:         True
        VTK:
            Enable:             False
            max_output_files:   1000
        ROOT:
            Enable:             True
            write_collisions:   True
        Binary:
            Enable:             True

            # print only particles in the end of event
            only_final:         False

            # write collisions (written to separate file)
            collisions_output:  True

            # write initial and final particles to collision file
            print_start_end:    True
        Yet_another_format:
            Enable:             True

    # how much time before recording measurables
    OUTPUT_INTERVAL:  1.0

    # initial random seed (negative for time)
    RANDOMSEED:    1

    # elastic cross section
    SIGMA:         10.0

    # number of test particle
    TESTPARTICLES: 1

    # number of events
    NEVENTS:       1

Modi:
    Box:
        # Cube size
        LENGTH: 10.0

        # initialization temperature
        TEMPERATURE: 0.2

        # initial condition
        #
        # 1:  random position box + thermal momenta
        # 2:  random position box + peaked momenta
        #
        INITIAL_CONDITION: 1

        # start time of simulation
        START_TIME:    0.0

    Sphere:
        # Sphere size
        RADIUS: 5.0

    Collider:
        # Projectile particle
        PROJECTILE: 211

        # Target particle
        TARGET: -211

        # center-of-mass energy in GeV
        SQRTS: 1.0
    Nucleus:
        # Definitions for the projectile:
        # Deuteron
        Projectile:
            PARTICLES: {2212: 1, 2112: 1}
            # very hard Woods-Saxon distribution.
            DIFFUSIVENESS: .001
        # Definitions for the target:
        # Lead
        Target:
            PARTICLES: {2212: 82, 2112: 126}

        # what sqrt(s_NN) to use:
        SQRTSNN: 2
        # which subsystem "NN" in sqrt(s_NN) refers to
        # (two PDG IDs). The default is proton-proton; let's set it to
        # neutron-neutron.
        SQRTS_N: [2112, 2112]
