General:
    # Modus decision
    MODUS:         Nucleus

    # temporal grid spacing
    DELTA_TIME:    0.01

    # end time of simulation
    END_TIME:      50.0

    # how much time before recording measurables
    OUTPUT_INTERVAL:  1

    # initial random seed (negative for time)
    RANDOMSEED:    -1

    # elastic cross section
    SIGMA:         10.0

    # number of test particle
    TESTPARTICLES: 1

    # number of events
    NEVENTS:       1

Modi:
    Box:
        # Cube size
        LENGTH: 10.0

        # initialization temperature
        TEMPERATURE: 0.2

        # initial condition
        #
        # 1:  random position box + thermal momenta
        # 2:  random position box + peaked momenta
        #
        INITIAL_CONDITION: 1

        # start time of simulation
        START_TIME:    0.0

    Sphere:
        # Sphere size
        RADIUS: 5.0

    Collider:
        # Projectile particle
        PROJECTILE: 211

        # Target particle
        TARGET: -211

        # center-of-mass energy in GeV
        SQRTS: 1.0
    Nucleus:
        # Definitions for the projectile:
        Projectile:
            PARTICLES: {2212: 92, 2112: 146}
            AUTOMATIC: 1
        # Definitions for the target:
        Target:
            PARTICLES: {2212: 92, 2112: 146}
            AUTOMATIC: 1

        # what sqrt(s_NN) to use:
        SQRTSNN: 193
        # which subsystem "NN" in sqrt(s_NN) refers to
        # (two PDG IDs). The default is proton-proton; let's set it to
        # neutron-neutron.
        SQRTS_N: [2112, 2112]
        # the initial z distance
        INITIAL_DISTANCE: 20
